/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    {
      type: 'category',
      label: 'CoreLib',
      items: ['main', 'data_layers', 'project_structure', 'basic_classes', 'rules_validator', 'session_manager', 'job', 'factory', 'observer', 'cache', 'helpers', 'web', 'datetime_utils', 'error_handler', 'function_utils', 'result_to_dict', 'strings', 'validation', 'soft_delete', 'default_registry', 'crud', 'handle_exceptions', 'logger', 'data_transform_helpers', 'instantiate_config'],
    },
    {
      type: 'category',
      label: 'Library your WEB Application',
      items: ['article_main', 'article_expected_outcome', 'article_responsibilities', 'article_layers'],
    },

  ],
};

module.exports = sidebars;
